###################
# rfsoc100 Config #
###################
---
sess_id: null

# bid.drid (Board ID & Drone ID)
com_to: '1.1'
udp_source_ip: '192.168.3.62'
udp_source_port: 4096

# Tone configuration
tones:
  NCLO: 512                    # Numerically controlled oscillator frequency (in MHz)
  full_bandwidth: 512          # Full bandwidth of sweeps (in MHz)
  chan_bw: 0.5                 # Bandwidth of each target sweep tone (in MHz) 
  sweep_steps: 500             # Number of points of each target sweep tone
  num_tones: null
  tone_freqs: null
  tone_powers: null
  tone_phis: null
  custom:
    tone_freqs: []
    tone_powers: []
    tone_phis: []
    generation:
      gen_attempts: 10             # Number of attempts to generate phases for given frequency and amplitude comb
      rescale_power: False         # Whether to rescale amplitudes if power exceeds DAC limit

# Attenuator configuration
atten:
  drive: 0 # Drive (DAC) attenuation in dB (float between 0 and 31.75)
  sense: 0  # Sense (ADC) attenuation in dB (float between 0 and 31.75)

# Detector configuration
det_config:
  network: "loopback" # Array.Network
  detector_type: "loopback" # Material of detectors
  nominal_num_detectors: 0
  nominal_detector_freqs: [] # Units of Hz

  found_num_detectors: null # Number of detectors found using find_detectors method
  found_detector_freqs: null # Array of found detector frequencies
  found_detector_freqs_filtered: null

det_find:
  peak_prom_std: 2
  peak_prom_db: 0
  peak_dis: 50
  width_min: 5
  width_max: 800
  stitch: True
  stitch_sw: 100
  continuum_wn: 300
  remove_cont: True
  remove_noise: True
  noise_wn: 30000

ADC_RMS: null
---
sess_id: null

# bid.drid (Board ID & Drone ID)
com_to: '1.2'
udp_source_ip: '192.168.3.63'
udp_source_port: 4096

# Tone configuration
tones:
  NCLO: 512                    # Numerically controlled oscillator frequency (in MHz)
  full_bandwidth: 512          # Full bandwidth of sweeps (in MHz)
  chan_bw: 0.5                 # Bandwidth of each target sweep tone
  sweep_steps: 500             # Number of points of each target sweep tone 
  num_tones: null
  tone_freqs: null
  tone_powers: null
  tone_phis: null
  custom:
    tone_freqs: []
    tone_powers: []
    tone_phis: []
    generation:
      gen_attempts: 10             # Number of attempts to generate phases for given frequency and amplitude comb
      rescale_power: False         # Whether to rescale amplitudes if power exceeds DAC limit

# Attenuator configuration
atten:
  drive: 0  # Drive (DAC) attenuation in dB (float between 0 and 31.75)
  sense: 0  # Sense (ADC) attenuation in dB (float between 0 and 31.75)

# Detector configuration
det_config:
  network: "loopback" # Array.Network
  detector_type: "loopback" # Material of detectors
  nominal_num_detectors: 0
  nominal_detector_freqs: [] # Units of Hz

  found_num_detectors: null # Number of detectors found using find_detectors method
  found_detector_freqs: null # Array of found detector frequencies
  found_detector_freqs_filtered: null

det_find:
  peak_prom_std: 2
  peak_prom_db: 0
  peak_dis: 50
  width_min: 5
  width_max: 800
  stitch: True
  stitch_sw: 100
  continuum_wn: 300
  remove_cont: True
  remove_noise: True
  noise_wn: 30000

ADC_RMS: null
---
sess_id: null

# bid.drid (Board ID & Drone ID)
com_to: '1.3'
udp_source_ip: '192.168.3.64'
udp_source_port: 4096


# Tone configuration
tones:
  NCLO: 512                    # Numerically controlled oscillator frequency (in MHz)
  full_bandwidth: 512          # Full bandwidth of sweeps (in MHz)
  chan_bw: 0.5                 # Bandwidth of each target sweep tone
  sweep_steps: 500                  # Number of points of each target sweep tone
  num_tones: null
  tone_freqs: null
  tone_powers: null
  tone_phis: null
  custom:
    tone_freqs: []
    tone_powers: []
    tone_phis: []
    generation:
      gen_attempts: 10             # Number of attempts to generate phases for given frequency and amplitude comb
      rescale_power: False         # Whether to rescale amplitudes if power exceeds DAC limit

# Attenuator configuration
atten:
  drive: 0 # Drive (DAC) attenuation in dB (float between 0 and 31.75)
  sense: 0  # Sense (ADC) attenuation in dB (float between 0 and 31.75)

# Detector configuration
det_config:
  network: "loopback"
  detector_type: "loopback" # Material of detectors
  nominal_num_detectors: 0
  nominal_detector_freqs: [] # Units of Hz

  found_num_detectors: null # Number of detectors found using find_detectors method
  found_detector_freqs: null # Array of found detector frequencies
  found_detector_freqs_filtered: null

det_find:
  peak_prom_std: 2
  peak_prom_db: 0
  peak_dis: 50
  width_min: 5
  width_max: 800
  stitch: True
  stitch_sw: 100
  continuum_wn: 300
  remove_cont: True
  remove_noise: True
  noise_wn: 30000

ADC_RMS: null
---
sess_id: null

# bid.drid (Board ID & Drone ID)
com_to: '1.4'
udp_source_ip: '192.168.3.65'
udp_source_port: 4096

# Tone configuration
tones:
  NCLO: 512                   # Numerically controlled oscillator frequency (in MHz)
  full_bandwidth: 512          # Full bandwidth of sweeps (in MHz)
  chan_bw: 0.5          # Bandwidth of each target sweep tone
  sweep_steps: 500             # Number of points of each target sweep tone
  num_tones: null
  tone_freqs: null
  tone_powers: null
  tone_phis: null
  custom:
    tone_freqs: []
    tone_powers: []
    tone_phis: []
    generation:
      gen_attempts: 10             # Number of attempts to generate phases for given frequency and amplitude comb
      rescale_power: False         # Whether to rescale amplitudes if power exceeds DAC limit

# Attenuator configuration
atten:
  drive: 0 # Drive (DAC) attenuation in dB (float between 0 and 31.75)
  sense: 0  # Sense (ADC) attenuation in dB (float between 0 and 31.75)

# Detector configuration
det_config:
  network: "loopback"
  detector_type: "loopback" # Material of detectors
  nominal_num_detectors: 0
  nominal_detector_freqs: [] # Units of Hz

  found_num_detectors: null # Number of detectors found using find_detectors method
  found_detector_freqs: null   # Array of found detector frequencies
  found_detector_freqs_filtered: null

det_find:
  peak_prom_std: 2
  peak_prom_db: 0
  peak_dis: 50
  width_min: 5
  width_max: 800
  stitch: True
  stitch_sw: 100
  continuum_wn: 300
  remove_cont: True
  remove_noise: True
  noise_wn: 30000

ADC_RMS: null
...















