---
sess_id: null

##############################
# External System Parameters #
##############################

# Add external system parameters that change over the course of data acquisiton here
avail_space: null # Available space on board in GB
power_supply_current: null
power_supply_voltage: null
array_temp: null
coldload_temp: null
temp_time: null
bath_temp: null

---
sess_id: null

###########################
# Drone/Board List Config #
###########################

drone_list: ['1.1','1.4'] # List of boards/drones to use

initialize: True
parallel: False # Whether to send commands to all drones in parallel (will stop all drones not in drone_list)
restart: False # Whether to restart already running drones

# Board configuration
udp_ip: "192.168.3.40"
udp_port: 4096
boards:
  b1: 
    board_ip: '192.168.2.99'
    sampling_freq: 488.28 # Timestream sampling frequency (Hz)
    drone_cfg: "/home/rfsoc/ccatkidlib/scripts/modcam_coldload/coldload_drone_config.yaml"
  b2:
    board_ip: '192.168.2.98'
    sampling_freq: 488.28 # Timestream sampling frequency
    drone_cfg: "/home/rfsoc/ccatkidlib/rfsoc/drones_config_2.yaml"

##################
# File IO Config #
##################

# File paths
file_paths:
  analysis_dir: "/home/rfsoc/ccatkidlib/analysis/"                         # Analysis code directory
  data_dir: "/mnt/md0/modcam_coldload_data"                                # Directory to save data in
  tmp_data_dir: "/home/rfsoc/primecam_readout/src/tmp"                     # Temp data directory in which primecam_readout saves files
  primecam_readout: "/home/rfsoc/primecam_readout/src/"                    # Primecam_readout source code directory
  master_drone_list: "/home/rfsoc/primecam_readout/master_drone_list.yaml" # Master Drone List File
  pcs_dir: "/home/rfsoc/ocs-site-configs/"                                 # PCS directory
  RSA_key: "/home/rfsoc/.ssh/xilinx"                                       # Path to RSA key (None if no key)
  drone_dir: "/home/xilinx/primecam_readout/drones"                        # Drone directory on the boards

# File names
file_names:
  stream_fname: 'coldload_tstream' # Timestream file name
  targ_fname: 'coldload_targ'      # Target sweep file name
  vna_fname: 'coldload_vna'        # VNA sweep file name
  comb_freq: 'f_rf_tones_comb'     # File head of comb frequency array
  comb_amp: 'a_tones_comb'         # File head of comb power array
  comb_phi: 'p_tones_comb'         # File head of comb phi array

# PCS agent IDs
pcs_agents:
  rfsoc_agent: "queenagent" # RFSoC agent ID 

# Runtime IO config
io:
  logging_level: 'INFO'
  logging_fname: "rfsoc_daq_log.txt"
  terminal_output: True  # Whether to print logs to terminal
  save_data: True        # Whether to save data
  save_config_copy: True # Whether to sawe copy of config (Recommended to use True)
  max_file_size: 50     # Max file size of timestreams in Megabytes
...
