---
tones:
  max_tones: 1000 # * Max number of tones per data file

file_paths:
  root_data_dir: '/mnt/md0/cooldown_202510' # * Root directory of data
  g3_root_dir: '/mnt/md0' # * Root directory of g3 timestream data
  fit_dir: '/home/jovyan/fitting' # * Directory containing external detector fitting code
  original_root_data_dir: '/mnt/md0/cooldown_october' # * Root directory where data was originally saved. Necessary for data taken before 10/2025.
  original_g3_root_dir: '/mnt/md0/' # * Root directory where g3 timestream data was originally saved. Only necessary for data taken before 10/2025.


io:
  file_logging:
    network_level: 'INFO'  # * File logging level for messages from Network objects
    detector_level: 'INFO' # * File logging level for messages from Detector objects
    data_level: 'CRITICAL' # * File logging level for messages from Data objects (and subclasses)
    logging_root_dir: '/mnt/md0/cooldown_202510' # * Root directory where log files should be saved
    logging_fname: 'analysis.log' # * Logging file name
    max_size: 100          # Max log file size before file rotation (in Megabytes)
  terminal_logging: 
    network_level: 'INFO'  # * Terminal logging level for messages from Network objects
    detector_level: 'INFO' # * Terminal logging level for messages from Detector objects
    data_level: 'CRITICAL' # * Terminal logging level for messages from Data objects (and subclasses)
  pickle:
    pickle_root_dir: '/mnt/md0/cooldown_202510' # Root directory where pickle files should be saved
    curr_pickle_root_dir: '' # Current path to root directory containing pickle file to load. Only necessary if pickle directory is moved.
    pickle_dataframes: False    # Whether to pickle properties and data DataFrames or save them as seperate parquet files (Recommended: False)
    overwrite: False # Whether to overwrite already existing pickle and parquet files

---
static_plot:
  sweep:
    aspect: 1
    fig_size: 100
    marker: 'o'
    marker_size: 3
    linewidth: 1
    tone_marker: '*'
    tone_marker_size: 9
    area_alpha: 0.25
  stream:
    aspect: 1
    fig_size: 100
    marker: 'o'
    marker_size: 3
    linewidth: 1
    datashade: True
  histogram:
    plot_median: True
    aspect: 1
    fig_size: 100
    cmap: 'viridis'
    linewidth: 3
    linestyle: '--'
save:
  save_fig: True   # Whether to automatically save figures generated by built-in plotting methods
  overwrite: False # Whether to overwrite figures with the same file name
  fig_root_dir: '/mnt/md0/cooldown_202510' # Root directory where figures should be saved
  fig_fmt: 'png' # Format to save figure (valid formats are png, jpeg, html, svg)
  figs_per_file: 144 # Maximum number of figures to include per file
...