---
file_paths:
  root_data_dir: '/mnt/md0/cooldown_june/'
  g3_root_dir: '/mnt/md0/'
  fit_dir: '/home/jovyan/fitting'

io:
  file_level: 'DEBUG'    # * File logging level
  terminal_level: 'INFO' # * Terminal logging level 
  logging_dir: ""        # * Logging directory. Will create log in ccatkidlib/logs if ""

---
plot_defaults:
  figure:
    width: 400
    height: 400
    toolbar_location: "left"
    tools: 'hover, box_select, box_zoom, undo, redo, reset, save'
    resizable: True
    sizing_mode: 'stretch_width'
    output_backend: 'webgl'
  line_scatter:
    plot_line: True
    line:
      line_color: '#1F77B4'
      line_width: 1
      line_alpha: 1
      line_dash: 'solid'
    plot_scatter: True
    scatter:
      marker: 'circle'
      size: 4
      fill_color: 'orange'
      fill_alpha: 0.5
      line_color: 'black'
      line_width: 1
      line_alpha: 0.5
      line_dash: 'solid'
  res:
    plot_line: False
    line:
      line_color: 'red'
      line_width: 0.5
      line_alpha: 0.75
      line_dash: 'solid'
    plot_scatter: True
    scatter:
      marker: 'star'
      size: 4
      fill_color: 'red'
      fill_alpha: 0.5
      line_color: 'black'
      line_width: 1
      line_alpha: 1
      line_dash: 'solid'
  binboxes:
    enable: True

    
plot_output:
  save_fig: True
  save_type: 'png' # Valid file types are png, svg, jpeg
  save_path: 'fig'

...