#=========================================#
# Example ccatkidlib System Config   2025 #
# Darshan Patel         dp649@cornell.edu #
#=========================================#

# ============================================================================================= #
# Parameters with * are measurment specific, ? are system specific, and - should not be edited  #
# ============================================================================================= #

---
sess_id: null

##############################
# External System Parameters #
##############################

# - Board properties
boards:
  b1:
    avail_space: null
    ps_temp: null
    pl_temp: null

---

# Create Jinja variables for values used more than once
{% set measurement_name="NAME_HERE" %}   # * Measurement Name
{% set root_dir="ROOT_DIR_HERE" %}       # * Root data directory for storing ccatkidlib data files (the part of the path that would change when transferring data to different drive)
{% set g3_root_dir="G3_ROOT_DIR_HERE" %} # * Root data directory for storing timestream G3 files (the part of the path that would change when transferring data to different drive)
{% set drone_dir="DRONE_CONFIGS_DIR_HERE" %} # * Directory where drone config files are stored

sess_id: null
name: {{measurement_name}} # * Measurement Name
desc: "DESC_HERE"          # * Description of measurement

###########################
# Drone/Board List Config #
###########################

# Drone configuration
drone_list: ['1', '2.1'] # *List of boards/drones to use. Can either specify entire boards (e.g. '1') or individual drones (e.g. '1.2')

init:
  initialize_boards: True   # * Whether to reintialize boards
  initialize_drones: True   # * Whether to run drone initialize commands (e.g. set_atten and setNCLO)
  restart: False            # * Whether to restart already running drones

runtime:
  parallel_boards: -1 # * Number of boards to run in parallel (-1 for all boards in parallel)
  parallel_drones: 4  # * Number of drones to run in in parallel  

# Board configuration
boards:
  b1: 
    name: rfsoc99              # ? Name of RFSoC (CCAT naming convention, not used for anything)
    board_ip: '192.168.2.99'   # ? Board IP address
    sampling_freq: 488.28      # - Timestream sampling frequency (in Hz) (Does not currently set the sampling frequency)
    max_power: 32767           # - Max power at the drone DACs
    drone_cfg: "{{drone_dir}}/DRONE_CFG_FILE" # * Drone configuration file

# Timestream configuration
timestream:
  udp_ip: "192.168.3.40"  # ? Control computer UDP packet capture port IP address
  udp_port: 4096          # ? Control computer UDP packet capture port number
  g3: True                # * Whether to save timestreams as g3 files
  file_rotation_time: 600 # * Length of timestream files (in seconds) (for npy timestreams)
  save_interval: 3        # * Length of time after which to save data in timestream buffer (in seconds) (for npy timestreams)

# PCS agent IDs
pcs_agents:
  rfsoc_agent: "det-queenagent" # ? RFSoC agent ID 

##################
# File IO Config #
##################

# File paths
file_paths:
  root_dir: "{{root_dir}}"                       # * Root data directory for storing ccatkidlib data files (the part of the path that would change when transferring data to different drive)
  g3_root_dir: "{{g3_root_dir}}"                 # * Root data directory for storing timestream G3 files (the part of the path that would change when transferring data to different drive)
  data_dir: "{{root_dir}}/{{measurement_name}}"  # * Directory to save data in
  g3_dir:   "{{g3_root_dir}}/g3/g3"              # ? Directory where g3 files are saved (as specified in rfsoc-streamer config)
  
  
  primecam_readout: "/home/rfsoc/primecam_readout/src/"                    # ? Primecam_readout source code directory
  master_drone_list: "/home/rfsoc/primecam_readout/master_drone_list.yaml" # ? Master drone list config file path
  pcs_dir: "/home/rfsoc/ocs-site-configs/"                                 # ? OCS directory with default.yaml file
  ssh_key: "/home/rfsoc/.ssh/id_ecdsa"                                     # ? Path to private ssh key (null if no key)
  drone_dir: "/home/xilinx/primecam_readout/drones"                        # - Drone directory on the boards

# * File names of saved data files
save_file_names:
  timestream: '{{measurement_name}}_tstream' # * Timestream file name
  targ_sweep: '{{measurement_name}}_targ'    # * Target sweep file name
  vna_sweep:  '{{measurement_name}}_vna'     # * VNA sweep file name

# - Names of files on RFSoC boards
board_file_names:
  vna:
    s21: 's21_vna'
    res: 'f_res_vna'
    comb_freq: 'freqs_vna'
    comb_amp:  'amps_vna'
    comb_phi:  'phis_vna'
  targ:
    s21: 's21_targ'
    res: 'f_res_targ'
    comb_freq: 'f_rf_tones_comb'
    comb_amp:  'a_tones_comb'
    comb_phi:  'p_tones_comb'

clean:
  threshold: 10       # * Remaining disk space in GB after which boards should be automatically cleaned (negative number for no auto cleaning)
  olderThanDaysAgo: 1 # * (days) Clean files older than specified number of days
  ftype: '.npy'       # * File type to clean
  tmp: True           # * Whether to clean tmp primecam_readout and ccatkidlib directories on control computer

# Runtime IO config
io:
  file_level: 'DEBUG'                                  # * File logging level
  terminal_level: 'INFO'                               # * Terminal logging level 
  logging_fname: "ccatkidlib_{{measurement_name}}.log" # * Log file name
  max_size: 100 # Max log file size in mega bytes
  influx_output: True                                  # * Whether to push measurement info to InfluxDB through the queen_agent
  save_data: True                                      # * Whether to save data
  save_config_copy: True                               # * Whether to save copy of config (Recommended to use True)
...
