#=========================================#
# Example ccatkidlib Drone Config    2025 #
# Darshan Patel         dp649@cornell.edu #
#=========================================#

# ============================================================================================= #
# Parameters with * are measurment specific, ? are system specific, and - should not be edited  #
# ============================================================================================= #

---
sess_id: null

# Drone configuration
com_to: '1.1'                 # ? bid.drid (Board ID & Drone ID)
udp_source_ip: '192.168.3.50' # ? UDP IP address of drone used for timestreaming
udp_source_port: 4096         # ? UDP port

# Tone configuration
tones:
  NCLO: 257                # * Numerically controlled local oscillator frequency (in MHz)
  full_bandwidth: 512      # - Full bandwidth of sweeps (in MHz) (cannot change currently)
  chan_bw: 0.5             # * Bandwidth of each target sweep tone (in MHz) 
  sweep_steps: 500         # * Number of points of each target sweep tone
  num_tones: null          # - Number of tones
  tone_freqs: null         # - Tone frequencies of most recent comb 
  tone_powers: null        # - Tone powers of most recent comb
  tone_phis: null          # - Tone phases of most recent comb
  noise_tones: []          # * Indicies of noise tones in most recent comb
  custom:
    tone_freqs: []         # * Custom tone frequencies as float, list of floats, or npy file path (in Hz)
    tone_powers: []        # * Custom tone powers as float, list of floats, or npy file path
    tone_phis: []          # * Custom tone phases as float, list of floats, or npy file path (in radians)
    generation:
      gen_attempts: 5      # * Number of attempts to randomly generate phases for given frequency and amplitude comb to minimize crest factor
      rescale_power: False # * Whether to rescale amplitudes if power exceeds DAC limit
  noise:
    tone_freqs: []         # * Noise tone frequencies as float, list of floats, or npy file path (in Hz) 
    tone_powers: []        # * Noise tone powers as float, list of floats, or npy file path
    tone_phis: []          # * Noise tone phases as float, list of floats, or npy file path (in radians)

# * Attenuator configuration (if using bulit in digital attenuators)
atten:
  drive: 15 # * Drive (DAC) attenuation in dB (float between 0 and 31.75)
  sense: 15 # * Sense (ADC) attenuation in dB (float between 0 and 31.75)

# * Detector configuration
det_config:
  network: "loopback"        # * Array.Network (naming convention for CCAT detector array networks, not used for anything)
  detector_type: "loopback"  # * Material of detectors (for logging purposes, not used for anything)
  nominal_num_detectors: 0   # * Nominal number of detectors being measured (for logging purposes, not used for anything)
  nominal_detector_freqs: [] # * Nominal resonant frequencies of detectors being measured (for logging purposes, not used for anything)

  found_num_detectors: null           # * Number of detectors found using find_detectors method
  found_detector_freqs: null          # * Found detector frequencies
  found_detector_freqs_filtered: null # * Number of detector retained after filtering

# * primecam_readout detector finding parameters
det_find:
  peak_prom_std: 2
  peak_prom_db: 0
  peak_dis: 50
  width_min: 5
  width_max: 800
  stitch: True
  stitch_sw: 100
  continuum_wn: 300
  remove_cont: True
  remove_noise: True
  noise_wn: 30000
  phase_filter: True
  filter_wn: 3

tune_placement:
  method: 'min' # Method for tuning tone placement: Must be one of 'min', 'grad'
  grad:
    trim:
      window: 2 # Number of FWHMs around minimum to keep
      savgol_window: 9 # Window size to use for savgol filter on |S_21| data to estimate FWHM. Use a window of 1 to specify no filtering
      savgol_order: 1 # Polynomial order to use for savgol filter
    diff:
      savgol_window: 21 # Window size to use for savgol filter on I & Q data for calculating derivatives. Use a window of 1 to specify no filtering
      savgol_order: 1 # Polynomial order to use for savgol filter

ADC_RMS: null # * RMS power measured at the ADC
---
sess_id: null

# Drone configuration
com_to: '1.2'                 # ? bid.drid (Board ID & Drone ID)
udp_source_ip: '192.168.3.51' # ? UDP IP address of drone used for timestreaming
udp_source_port: 4096         # ? UDP port

# Tone configuration
tones:
  NCLO: 257                # * Numerically controlled local oscillator frequency (in MHz)
  full_bandwidth: 512      # - Full bandwidth of sweeps (in MHz) (cannot change currently)
  chan_bw: 0.5             # * Bandwidth of each target sweep tone (in MHz) 
  sweep_steps: 500         # * Number of points of each target sweep tone
  num_tones: null          # - Number of tones
  tone_freqs: null         # - Tone frequencies of most recent comb 
  tone_powers: null        # - Tone powers of most recent comb
  tone_phis: null          # - Tone phases of most recent comb
  custom:
    tone_freqs: []         # * Custom tone frequencies as float, list of floats, or npy file path (in Hz)
    tone_powers: []        # * Custom tone powers as float, list of floats, or npy file path
    tone_phis: []          # * Custom tone phases as float, list of floats, or npy file path (in radians)
    generation:
      gen_attempts: 5      # * Number of attempts to randomly generate phases for given frequency and amplitude comb to minimize crest factor
      rescale_power: False # * Whether to rescale amplitudes if power exceeds DAC limit
  noise:
    tone_freqs: []         # * Noise tone frequencies as float, list of floats, or npy file path (in Hz) 
    tone_powers: []        # * Noise tone powers as float, list of floats, or npy file path
    tone_phis: []          # * Noise tone phases as float, list of floats, or npy file path (in radians)

# * Attenuator configuration (if using bulit in digital attenuators)
atten:
  drive: 15 # * Drive (DAC) attenuation in dB (float between 0 and 31.75)
  sense: 15 # * Sense (ADC) attenuation in dB (float between 0 and 31.75)

# * Detector configuration
det_config:
  network: "loopback"        # * Array.Network (naming convention for CCAT detector array networks, not used for anything)
  detector_type: "loopback"  # * Material of detectors (for logging purposes, not used for anything)
  nominal_num_detectors: 0   # * Nominal number of detectors being measured (for logging purposes, not used for anything)
  nominal_detector_freqs: [] # * Nominal resonant frequencies of detectors being measured (for logging purposes, not used for anything)

  found_num_detectors: null           # * Number of detectors found using find_detectors method
  found_detector_freqs: null          # * Found detector frequencies
  found_detector_freqs_filtered: null # * Number of detector retained after filtering

# * primecam_readout detector finding parameters
det_find:
  peak_prom_std: 2
  peak_prom_db: 0
  peak_dis: 50
  width_min: 5
  width_max: 800
  stitch: True
  stitch_sw: 100
  continuum_wn: 300
  remove_cont: True
  remove_noise: True
  noise_wn: 30000
  phase_filter: True
  filter_wn: 3

tune_placement:
  method: 'min' # Method for tuning tone placement: Must be one of 'min', 'grad'
  grad:
    trim:
      window: 2 # Number of FWHMs around minimum to keep
      savgol_window: 9 # Window size to use for savgol filter on |S_21| data to estimate FWHM. Use a window of 1 to specify no filtering
      savgol_order: 1 # Polynomial order to use for savgol filter
    diff:
      savgol_window: 21 # Window size to use for savgol filter on I & Q data for calculating derivatives. Use a window of 1 to specify no filtering
      savgol_order: 1 # Polynomial order to use for savgol filter
      
ADC_RMS: null # * RMS power measured at the ADC
---
sess_id: null

# Drone configuration
com_to: '1.3'                 # ? bid.drid (Board ID & Drone ID)
udp_source_ip: '192.168.3.52' # ? UDP IP address of drone used for timestreaming
udp_source_port: 4096         # ? UDP port

# Tone configuration
tones:
  NCLO: 257                # * Numerically controlled local oscillator frequency (in MHz)
  full_bandwidth: 512      # - Full bandwidth of sweeps (in MHz) (cannot change currently)
  chan_bw: 0.5             # * Bandwidth of each target sweep tone (in MHz) 
  sweep_steps: 500         # * Number of points of each target sweep tone
  num_tones: null          # - Number of tones
  tone_freqs: null         # - Tone frequencies of most recent comb 
  tone_powers: null        # - Tone powers of most recent comb
  tone_phis: null          # - Tone phases of most recent comb
  custom:
    tone_freqs: []         # * Custom tone frequencies as float, list of floats, or npy file path (in Hz)
    tone_powers: []        # * Custom tone powers as float, list of floats, or npy file path
    tone_phis: []          # * Custom tone phases as float, list of floats, or npy file path (in radians)
    generation:
      gen_attempts: 5      # * Number of attempts to randomly generate phases for given frequency and amplitude comb to minimize crest factor
      rescale_power: False # * Whether to rescale amplitudes if power exceeds DAC limit
  noise:
    tone_freqs: []         # * Noise tone frequencies as float, list of floats, or npy file path (in Hz) 
    tone_powers: []        # * Noise tone powers as float, list of floats, or npy file path
    tone_phis: []          # * Noise tone phases as float, list of floats, or npy file path (in radians)
# * Attenuator configuration (if using bulit in digital attenuators)
atten:
  drive: 15 # * Drive (DAC) attenuation in dB (float between 0 and 31.75)
  sense: 15 # * Sense (ADC) attenuation in dB (float between 0 and 31.75)

# * Detector configuration
det_config:
  network: "loopback"        # * Array.Network (naming convention for CCAT detector array networks, not used for anything)
  detector_type: "loopback"  # * Material of detectors (for logging purposes, not used for anything)
  nominal_num_detectors: 0   # * Nominal number of detectors being measured (for logging purposes, not used for anything)
  nominal_detector_freqs: [] # * Nominal resonant frequencies of detectors being measured (for logging purposes, not used for anything)

  found_num_detectors: null           # * Number of detectors found using find_detectors method
  found_detector_freqs: null          # * Found detector frequencies
  found_detector_freqs_filtered: null # * Number of detector retained after filtering

# * primecam_readout detector finding parameters
det_find:
  peak_prom_std: 2
  peak_prom_db: 0
  peak_dis: 50
  width_min: 5
  width_max: 800
  stitch: True
  stitch_sw: 100
  continuum_wn: 300
  remove_cont: True
  remove_noise: True
  noise_wn: 30000
  phase_filter: True
  filter_wn: 3

tune_placement:
  method: 'min' # Method for tuning tone placement: Must be one of 'min', 'grad'
  grad:
    trim:
      window: 2 # Number of FWHMs around minimum to keep
      savgol_window: 9 # Window size to use for savgol filter on |S_21| data to estimate FWHM. Use a window of 1 to specify no filtering
      savgol_order: 1 # Polynomial order to use for savgol filter
    diff:
      savgol_window: 21 # Window size to use for savgol filter on I & Q data for calculating derivatives. Use a window of 1 to specify no filtering
      savgol_order: 1 # Polynomial order to use for savgol filter

ADC_RMS: null # * RMS power measured at the ADC
---
sess_id: null

# Drone configuration
com_to: '1.4'                 # ? bid.drid (Board ID & Drone ID)
udp_source_ip: '192.168.3.53' # ? UDP IP address of drone used for timestreaming
udp_source_port: 4096         # ? UDP port

# Tone configuration
tones:
  NCLO: 257                # * Numerically controlled local oscillator frequency (in MHz)
  full_bandwidth: 512      # - Full bandwidth of sweeps (in MHz) (cannot change currently)
  chan_bw: 0.5             # * Bandwidth of each target sweep tone (in MHz) 
  sweep_steps: 500         # * Number of points of each target sweep tone
  num_tones: null          # - Number of tones
  tone_freqs: null         # - Tone frequencies of most recent comb 
  tone_powers: null        # - Tone powers of most recent comb
  tone_phis: null          # - Tone phases of most recent comb
  custom:
    tone_freqs: []         # * Custom tone frequencies as float, list of floats, or npy file path (in Hz)
    tone_powers: []        # * Custom tone powers as float, list of floats, or npy file path
    tone_phis: []          # * Custom tone phases as float, list of floats, or npy file path (in radians)
    generation:
      gen_attempts: 5      # * Number of attempts to randomly generate phases for given frequency and amplitude comb to minimize crest factor
      rescale_power: False # * Whether to rescale amplitudes if power exceeds DAC limit
  noise:
    tone_freqs: []         # * Noise tone frequencies as float, list of floats, or npy file path (in Hz) 
    tone_powers: []        # * Noise tone powers as float, list of floats, or npy file path
    tone_phis: []          # * Noise tone phases as float, list of floats, or npy file path (in radians)

# * Attenuator configuration (if using bulit in digital attenuators)
atten:
  drive: 15 # * Drive (DAC) attenuation in dB (float between 0 and 31.75)
  sense: 15 # * Sense (ADC) attenuation in dB (float between 0 and 31.75)

# * Detector configuration
det_config:
  network: "loopback"        # * Array.Network (naming convention for CCAT detector array networks, not used for anything)
  detector_type: "loopback"  # * Material of detectors (for logging purposes, not used for anything)
  nominal_num_detectors: 0   # * Nominal number of detectors being measured (for logging purposes, not used for anything)
  nominal_detector_freqs: [] # * Nominal resonant frequencies of detectors being measured (for logging purposes, not used for anything)

  found_num_detectors: null           # * Number of detectors found using find_detectors method
  found_detector_freqs: null          # * Found detector frequencies
  found_detector_freqs_filtered: null # * Number of detector retained after filtering

# * primecam_readout detector finding parameters
det_find:
  peak_prom_std: 2
  peak_prom_db: 0
  peak_dis: 50
  width_min: 5
  width_max: 800
  stitch: True
  stitch_sw: 100
  continuum_wn: 300
  remove_cont: True
  remove_noise: True
  noise_wn: 30000
  phase_filter: True
  filter_wn: 3

tune_placement:
  method: 'min' # Method for tuning tone placement: Must be one of 'min', 'grad'
  grad:
    trim:
      window: 2 # Number of FWHMs around minimum to keep
      savgol_window: 9 # Window size to use for savgol filter on |S_21| data to estimate FWHM. Use a window of 1 to specify no filtering
      savgol_order: 1 # Polynomial order to use for savgol filter
    diff:
      savgol_window: 21 # Window size to use for savgol filter on I & Q data for calculating derivatives. Use a window of 1 to specify no filtering
      savgol_order: 1 # Polynomial order to use for savgol filter

ADC_RMS: null # * RMS power measured at the ADC
...

