---
sess_id: null

##############################
# External System Parameters #
##############################

# Add external system parameters that change over the course of data acquisiton here
avail_space: null # Available space on board in GB
bath_temp: null

---
sess_id: null

###########################
# Drone/Board List Config #
###########################

drone_list: ['1.2'] # List of boards/drones to use

initialize_boards: False # Whether to reintialize boards (not working in Jupyter Notebook right now)
initialize_drones: True # Whether to run drone initialzie commands (e.g. set_atten and setNCLO)
parallel: -1 # Whether to send commands to all drones in parallel (will stop all drones not in drone_list): -1 series, 0 all boards, 1 one board at a time
restart: False # Whether to restart already running drones

# Board configuration
udp_ip: "192.168.3.40"
udp_port: 4096
boards:
  b1: 
    name: rfsoc100
    board_ip: '192.168.2.100'
    sampling_freq: 488.28 # Timestream sampling frequency (in Hz)
    max_power: 32767 # Max power at the drone DACs
    drone_cfg: "/home/pcs/ccatkidlib/ccatkidlib/rfsoc/rfsoc100_config.yaml"
  b2:
    name: rfsoc101
    board_ip: '192.168.2.101'
    sampling_freq: 488.28 # Timestream sampling frequency
    max_power: 32767 # Max power at the drone DACs
    drone_cfg: "/home/pcs/ccatkidlib/ccatkidlib/rfsoc/rfsoc101_config.yaml"

##################
# File IO Config #
##################

# File paths
file_paths:
  data_dir: "/mnt/md0/cooldown_dec/timing"                             # Directory to save data in
  primecam_readout: "/home/pcs/primecam_readout/src/"                    # Primecam_readout source code directory
  master_drone_list: "/home/pcs/primecam_readout/master_drone_list.yaml" # Master Drone List File
  pcs_dir: "/home/ocs/pcs-site-configs/"                                 # PCS directory
  ssh_key: "/home/pcs/.ssh/id_ecdsa"                                     # Path to private ssh key (null if no key)
  drone_dir: "/home/xilinx/primecam_readout/drones"                      # Drone directory on the boards

# File names of saved data files
save_file_names:
  timestream: 'timing_tstream' # Timestream file name
  targ_sweep: 'timing_targ'    # Target sweep file name
  vna_sweep:  'timing_vna'     # VNA sweep file name

# Names of files on RFSoC boards
board_file_names:
  vna:
    s21: 's21_vna'
    res: 'f_res_vna'
    comb_freq: 'freqs_vna'
    comb_amp:  'amps_vna'
    comb_phi:  'phis_vna'
  targ:
    s21: 's21_targ'
    res: 'f_res_targ'
    comb_freq: 'f_rf_tones_comb'
    comb_amp:  'a_tones_comb'
    comb_phi:  'p_tones_comb'

# PCS agent IDs
pcs_agents:
  rfsoc_agent: "det-queenagent" # RFSoC agent ID 

# Runtime IO config
io:
  logging_level: 'INFO'
  logging_fname: "rfsoc_daq_log.txt"
  terminal_output: True   # Whether to print logs to terminal
  save_data: True         # Whether to save data
  from_board: True        # Whether to pull data directly from RFSoC board (slower) or from primecam_readout /src/tmp folder
  save_config_copy: True  # Whether to sawe copy of config (Recommended to use True)
  max_file_size: 2000     # Max file size of timestreams in Megabytes
...
