---
sess_id: None

# Config for data sets
paths:
  data_path : '/home/rfsoc/rfsoc_result/polarization/data/'
  date : '20241016'
  stamp: '1729099397'
  board: 'B1D1'

  output_path : '/home/rfsoc/Andy/pol_results'

# Timestream Denoise
timestream_denoise:
  window : 'gaussian'
  widths : [0.1, 1, 1]
  frequencies : [0, 10, 30]

# Plots and data io
io:
  plot_s21fits : True
  plot_phase_plots : True

  