# Module to handle fine sweep data to identify and place custom tones
import sys
sys.path.append("../analysis")
import numpy as np
import os


import resonator_model_v3 as rm

# Function to load fine sweep data
def load_fine_sweep(path_s21, path_f0, window=75.0e6):
    """
        What does this function do?
        
        path_s21 (str): path to np array generated by RFSoC containing complex transmission (s21) data from target sweep
        path_f0 (str): path to np array generated by RFSoC containing resonant freqs estimated by firmware peak-finder
        window (float): expected freq width (in Hz) for each resonators; will need to be reduced for arrays 
    """
    targ_sweep_s21 = np.load(path_s21, allow_pickle = True)
    rfsoc_f0s = np.load(data_dir + targ_sweep_f0s_fname).real
    f, s21 = targ_sweep_s21[0].real, targ_sweep_s21[1]
    for i in range(len(rfsoc_f0s)):
        f_range = f[np.abs(f - rfsoc_f0s[i]) < window]
        s21_range = s21[np.abs(f - rfsoc_f0s[i]) < window]
        resonators.append(resonator(f0=rfsoc_f0s[i], f=f_range, s21=s21_range))
	
    

    # Could be that you create a resonator object for each resonator - would need to import Res() from resonator.py

#    return array_of_res_objects

# Fit the fine sweep
def fit_resonator_resmodel3(resonators, nonlinear=False, asymm = False):
    """
    nonlinear (bool): fit IQ data to nonlinear resonator model?
    asymm (bool): fit IQ data to an asymm resonator model?
    """
    # Call a bunch of things from resonator_model_v3
    fitted_f0s = []
    for resonator in resonators:
        resonator.fit_resonator(nonlinear, asymm)
        fitted_f0s.append(resonator.params['f_0'].value)
    return fitted_f0s

def write_custom_freqs():
    """
    """
    os.system("scp " + tmpfnames[0] + " xilinx@192.168.2.98:/home/xilinx/CCATpHive/alcove_commands/custom_freqs.npy")

# Generating and copying over custom tone list
#def prepare_custom_tone_list():
#    """
#       Please write a docstring for each function, even if short!
#       Should include a description of each variable that needs to be passed in
#       and of what is returned (if anything) by the function
#    """
    # Generate tone list in appropriate format

    # scp tone list to RFSoC
